### ISSUE TITLE
update survey 

### ISSUE THREAD

**Issue by luoqishuai** [SupeRuier/awesome-active-learning#1]
https://arxiv.org/abs/2210.10109
A Survey of Active Learning for Natural Language Processing

**Comment by SupeRuier** [comment]
This survey had already been added to the following page (subpage of the AL applications): https://github.com/SupeRuier/awesome-active-learning/blob/master/contents/AL_combinations.md#natural-language-processing-nlp.

Since it focuses on one specific field (NLP), I didn't add it to the main page.
